### ISSUE TITLE
Wrong result in Satang convention

### ISSUE THREAD

**Issue by antronic** [antronic/thai-baht-text-js#13]
```
var thaiBahtText = require("thai-baht-text")

console.log(thaiBahtText(10055.123))
```

Outcome Result
` "หนึ่งหมื่นห้าสิบห้าบาทสิบสองสตางค์" `

Expected Result
` "หนึ่งหมื่นห้าสิบห้าบาทหนึ่งสองสามสตางค์" `

**Comment by icharge** [comment]
Should it be closed?
