### ISSUE TITLE
What should return when input is 101

### ISSUE THREAD

**Issue by bazsup** [antronic/thai-baht-text-js#14]
I want to know 101 should be `หนึ่งร้อยเอ็ดบาทถ้วน` or `หนึ่งร้อยหนึ่งบาทถ้วน`

**Comment by antronic** [comment]
It supposes to be `หนึ่งร้อยเอ็ดบาทถ้วน` ครับ

**Comment by bazsup** [comment]
@antronic Thanks a lot.
