### ISSUE TITLE
ห้าสิบสตางค์ต่อท้าย

### ISSUE THREAD

**Issue by Porrapat** [antronic/thai-baht-text-js#2]
จริงๆ ไม่ควรผลักภาระให้ User แปลง เลขเป็น String เอง

อย่างเช่น
ThaiBaht(100.5) // ควรได้ หนึ่งร้อยบาทห้าสิบสตางค์
ThaiBaht(100.50) // ควรได้ หนึ่งร้อยบาทห้าสิบสตางค์
ThaiBaht(100.500) // ควรได้ หนึ่งร้อยบาทห้าสิบสตางค์
ThaiBaht(100.501) // ควรได้ หนึ่งร้อยบาทห้าสิบสตางค์ // ปัดลง
ThaiBaht(100.500000001) // ควรได้ หนึ่งร้อยบาทห้าสิบสตางค์ // ปัดลง
ThaiBaht(100.505) // ควรได้ หนึ่งร้อยบาทห้าสิบเอ็ดสตางค์ // ปัดขึ้น
ThaiBaht(100.01) // ควรได้ หนึ่งร้อยบาทหนึ่งสตางค์ // ปัดขึ้น
ThaiBaht(100.005) // ควรได้ หนึ่งร้อยบาทหนึ่งสตางค์ // ปัดขึ้น
ThaiBaht(100.505) // ควรได้ หนึ่งร้อยบาทห้าสิบเอ็ดสตางค์ // ปัดขึ้น

**Comment by Porrapat** [comment]
แนะนำใส่ .toFixed(2) ไปก่อน 
อันนี้พอถูไถ แต่ก็ยังไม่สามารถผ่าน TestCase ทั้งหมดด้านบน

let money = 100.51
res.send(ThaiBaht(money.toFixed(2).toString()))

อยากให้พัฒนาเข้าไปภายในฟังก์ชันเลย
คนใช้ข้างนอกจะได้ไม่ต้องมาใส่เองนอก Module ครับ

**Comment by antronic** [comment]
บางทีเรา เอายาวของเลขทศนิยมมา fixed ตำแหน่งก็ได้นะครับ
const numberStr = '2.54355'
parseFloat(numberStr).toFixed(numberString.split('.')[1].length)

**Comment by antronic** [comment]
แก้เรียบร้อยแล้วครับ #แก้ขณะอยู่บนรถเมล์
